spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookingdb
    username: root
    password: rootroot

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8381

inventory-service:
  url: http://localhost:8103
booking-service:
  url: http://localhost:8081

#spring:
#  activemq:
#    broker-url: tcp://activemq:61616
#    user: admin
#    password: admin
#    in-memory: false