spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:mysql://localhost:3306/bookingdb
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring.activemq.broker-url: tcp://localhost:61616


inventory-service:
  url: http://localhost:8103

